package main

import (
	"fmt"
	"go-study/spider2"
	_ "net/http/pprof"
)

//func main()  {
//	go func() {
//		for {
//			fmt.Println("https://cto.sh.cn")
//			//break
//			time.Sleep(3 * time.Second)
//		}
//	}()
//
//	http.ListenAndServe("127.0.0.1:8888", nil)
//}

type AutoGenerated struct {
	Age   int    `json:"age"`
	Name  string `json:"name"`
	Child []int  `json:"child"`
}

func main() {
	//go hello()
	//fmt.Println("main goroutine done!")
	//fmt.Println(os.Args)
	spider2.Main()
}

func hello() {
	fmt.Println("Hello Goroutine!")
}
